name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  swiftLint:
    runs-on: macos-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      working-directory: carowash/carowash
      run: bundle install
    - name: Run swiftlint
      working-directory: carowash/carowash
      run: bundle exec fastlane swiftLintLane
